name: Python application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        poetry-version: [1.1.4]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry ${{ matrix.poetry-version }} for Python ${{ matrix.python-version }}
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry==${{ matrix.poetry-version }}
      env:
        POETRY_HOME: /home/runner/.poetry

    - name: Add Poetry to PATH
      run: echo "::add-path::/home/runner/.poetry/bin"

    - name: Verify Poetry installation
      run: poetry --version

    - name: Install dependencies
      shell: bash
      run: poetry install

    - name: Test
      run: |
        poetry run python manage.py test
